### ISSUE TITLE
Double slashes ("\\n") in listing15.go

### ISSUE THREAD

**Issue by jf** [goinaction/code#16]
https://github.com/goinaction/code/blob/master/chapter6/listing15/listing15.go#L48 and #L53

**Comment by jf** [comment]
uh, found another one in listing16.go as well? Decided to do a grep and found these:

```
1 chapter6/listing04/listing04.go:                fmt.Printf("%s:%d\\n", prefix, outer)
2 chapter6/listing15/listing15.go:                fmt.Printf("Doing %s Work\\n", name)
3 chapter6/listing15/listing15.go:                        fmt.Printf("Shutting %s Down\\n", name)
4 chapter6/listing16/listing16.go:        fmt.Printf("Final Counter: %d\\n", counter)
```

**Comment by ardan-bkennedy** [comment]
Thanks for this. The book required the \\ to display correctly. Must have pushed that back into the code :(. Thanks for bringing this to my attention. If you find anything please issue a PR if you like :)

**Comment by jf** [comment]
Gotcha. For now, I'm ok. I'm more concerned with the organization of the code as it is right now. I'll file another issue for that so we can have that discussion there instead. Thanks for fixing the slashes!
