### ISSUE TITLE
6-10 listing09.go

### ISSUE THREAD

**Issue by piperck** [goinaction/code#19]
This code can not get expected value..
The Final Counter will print 4 not 2.

**Comment by ardan-bkennedy** [comment]
I think this is the data race code. Can you put a link to the specific code you are talking about.

**Comment by piperck** [comment]
Thanks for reply.
URL:https://github.com/goinaction/code/blob/master/chapter6/listing09/listing09.go 
The code output " Final Counter will print 4 ", but the book(GO IN ACTION) says “Final Counter will print 2”.
Can you fix this? 
Thanks

**Comment by ardan-bkennedy** [comment]
If you are running this on Linux or the Mac, this call `runtime.Gosched()` will ask the scheduler to swap out the goroutine. This usually happens. I have seen on Windows the scheduler be less preemptive.

**Comment by piperck** [comment]
oh..I running this on Mac and use go version 1.8. It output 4.
You means swap out the goroutine may depends on os? 
....I cann't figure it out.

**Comment by ardan-bkennedy** [comment]
That call tells the scheduler to cooperate and allow the other goroutine to run. Basically forcing the data race. I have never seen that not work on the Mac. If you want we can jump on a ScreenHero

**Comment by ardan-bkennedy** [comment]
Check this out. https://play.golang.org/p/h9jpgaIO9F

**Comment by piperck** [comment]
Oh! I figure it out. Normally It output 4. I running again and again ..  Finally It output2 once.
I think it always force the data race before. 
And I try to use `go build -race` But nothing happened.
![](https://ww2.sinaimg.cn/large/006tKfTcly1fdnwpzygurj30os08ygnr.jpg)

**Comment by ardan-bkennedy** [comment]
The race detector should see that immediately. After you build with the race detector, you must run the program. Build does not run.

**Comment by piperck** [comment]
ok. I see.
Your book is very helpful.
Thanks for your patience.
