### ISSUE TITLE
chapter2

### ISSUE THREAD

**Issue by FaberNa** [goinaction/code#22]
Cannot resolve in main.go the 'log' and ' os' the others file contains the absolute path with github. But the remains two ( log and os ) is not present..

**Comment by FaberNa** [comment]
Sorry my mistake on log and OS i don't set GOROOT. but for the absolute path still remain error

**Comment by justajwolf** [comment]
I am very loss , for this code:https://github.com/goinaction/code/blob/master/chapter2/sample/search/match.go.
```
func Display(results chan *Result) {
	for result := range results {
		log.Printf("%s:\n%s\n\n", result.Field, result.Content)
	}
}
```
Above code，the "result" is a Point, is it not? and the "result.Field" can show the right result what we expect?
The right is following, is it not?
```
func Display(results chan *Result) {
	for result := range results {
		log.Printf("%s:\n%s\n\n",(*result).Field, (*result).Content)
	}
}
```

**Comment by ardan-bkennedy** [comment]
Not sure I understand the "Point" comments. This code is receiving values from the channel and displaying information from the Result value.
