### ISSUE TITLE
No need to import `encoding/xml` in listing 12

### ISSUE THREAD

**Issue by goku321** [goinaction/code#38]
We don't need to import `encoding/xml` in listing 12 as it is not being used anywhere in the code.
https://github.com/goinaction/code/blob/49fc99e6affb9aa48cab1889505aa6631ee31ace/chapter9/listing12/listing12_test.go#L6

**Comment by billhathaway** [comment]
The xml package is used at: https://github.com/goinaction/code/blob/49fc99e6affb9aa48cab1889505aa6631ee31ace/chapter9/listing12/listing12_test.go#L74

**Comment by goku321** [comment]
oops! @billhathaway my bad. I missed it. Thanks for pointing it out 😄
