### ISSUE TITLE
代码使用的go版本是什么版本？

### ISSUE THREAD

**Issue by mirgong** [goinaction/code#41]
代码使用的go版本是什么版本？
![Uploading image.png…]()
import (
	"fmt"
	"io/ioutil"
	"os"

	"github.com/goinaction/code/chapter3/words"
)

// main is the entry point for the application.
func main() {
	filename := os.Args[1]

	contents, err := ioutil.ReadFile(filename)
	if err != nil {
		fmt.Println("There was an error opening the file:", err)
		return
	}

	text := string(contents)

	count := words.CountWords(text)
	fmt.Printf("There are %d words in your text. \n", count)
}
运行结果：
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.main()

**Comment by MarcusMogg** [comment]
跟版本有什么关系，这是命令行没输入文件名……
