### ISSUE TITLE
Program to find sum of odd numbers from 1 to n.

### ISSUE THREAD

**Issue by itzmahi07** [goinaction/code#59]
#include <stdio.h>

int main()
{
    int i, n, sum=0;

   
    printf("Enter upper limit: ");
    scanf("%d", &n);

   
    for(i=1; i<=n; i+=2)
    {
        sum += i;
    }

    printf("Sum of odd numbers = %d", sum);

    return 0;
}

**Comment by ardan-bkennedy** [comment]
Why are you leaving these issues?

**Comment by itzmahi07** [comment]
Just saving them. Now i have my own repository. Sry for inconvenience

**Comment by itzmahi07** [comment]
But dont delete my created ones.

**Comment by ardan-bkennedy** [comment]
I will leave these for a week and then I will be deleting them.

**Comment by itzmahi07** [comment]
No plz leave these ones!! I have to send a link of these to my teacher as a assignment!🙏🏻

**Comment by ardan-bkennedy** [comment]
I can't leave this forever. It would be better to send a new link. Plus. You should be using the Go Playground.

https://play.golang.org/

**Comment by itzmahi07** [comment]
So then plz delete it now just to empty my issue section...then i would work again in my own repository....plz delete that all as soon as possible.....i have to sum up my work

**Comment by itzmahi07** [comment]
Can uh do thiss?. Plzz be quick!

**Comment by ardan-bkennedy** [comment]
I won't delete anything until you tell me you've transfered the examples over. My goal is not to have you fail, just move everything to the Go Playground for grading.

**Comment by itzmahi07** [comment]
Dudeee! What i m sayinn! Plzz delt that stuff now so my isssue section will be empty! Then I'll keep stuff in my repository!...
